### ISSUE TITLE
i have a question, can you help me ?

### ISSUE THREAD

**Issue by bluesiboy** [belik-alexandr94/AMD-Ryzentosh-Opencore#1]
i have a question, can you help me ?

my master board is b450M, cpu is r7 3800x , gpu is rx 580 4G.
mac can success boot , and use it !
but, my GPU meory is fill full, 
when this happens, screen is torn and frozen. 
and mouse is not moving, he is flashing!!! 
flash, you know this is skill  by LOL game.

**Comment by bluesiboy** [comment]
![QQ20200319-003141](https://user-images.githubusercontent.com/9855885/76984283-9467a080-6979-11ea-8d9f-373d113f45b2.png)
![QQ20200319-003206](https://user-images.githubusercontent.com/9855885/76984311-9b8eae80-6979-11ea-896e-2a0c6cd81aef.png)

![QQ20200319-002942](https://user-images.githubusercontent.com/9855885/76984245-89147500-6979-11ea-9e79-9750b6b8560b.png)
![QQ20200319-003024](https://user-images.githubusercontent.com/9855885/76984249-8a45a200-6979-11ea-9cab-b2a7b06b70a1.png)
![QQ20200319-003125](https://user-images.githubusercontent.com/9855885/76984259-8c0f6580-6979-11ea-9c49-7768afcd150d.png)

**Comment by belik-alexandr94** [comment]
> i have a question, can you help me ?
> 
> my master board is b450M, cpu is r7 3800x , gpu is rx 580 4G.
> mac can success boot , and use it !
> but, my GPU meory is fill full,
> when this happens, screen is torn and frozen.
> and mouse is not moving, he is flashing!!!
> flash, you know this is skill by LOL game.

Hi. Sorry, but i can't help you.  I just provided my current config here. 
Try to ask at forum: https://forum.amd-osx.com/
As I can see some users have problems with GPU hardware acceleration. You can try to find config for your RX580 at forum, maybe it helps.
